export const authConstants = {
  SIGNIN_REQUEST:'SIGNIN_REQUEST',
  SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
  SIGNIN_FAILURE:'SIGNIN_FAILURE',
  SIGNUP_REQUEST:'SIGNUP_REQUEST',
  SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
  SIGNUP_FAILURE:'SIGNUP_FAILURE',
  SIGNOUT_REQUEST:'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE:'SIGNOUT_FAILURE',
  LOGGEDIN_REQUEST:'LOGGEDIN_REQUEST',
  LOGGEDIN_SUCCESS:'LOGGEDIN_SUCCESS',
  LOGGEDIN_FAILURE:'LOGGEDIN_FAILURE',
}

export const getData = {
  GETDATA_REQUEST:'GETDATA_REQUEST',
  GETDATA_SUCCESS:'GETDATA_SUCCESS',
  GETDATA_FAILURE:'GETDATA_FAILURE',
}

export const addEducation = {
  ADD_EDUCATION_REQUEST:'ADD_EDUCATION_REQUEST',
  ADD_EDUCATION_SUCCESS:'ADD_EDUCATION_SUCCESS',
  ADD_EDUCATION_FAILURE:'ADD_EDUCATION_FAILURE',
}

export const addWorkExperience = {
  ADD_WORK_EXP_REQUEST:'ADD_WORK_EXP_REQUEST',
  ADD_WORK_EXP_SUCCESS:'ADD_WORK_EXP_SUCCESS',
  ADD_WORK_EXP_FAILURE:'ADD_WORK_EXP_FAILURE',
}
export const addNewRecruiter = {
  ADD_RECRUITER_REQUEST:'ADD_RECRUITER_REQUEST',
  ADD_RECRUITER_SUCCESS:'ADD_RECRUITER_SUCCESS',
  ADD_RECRUITER_FAILURE:'ADD_RECRUITER_FAILURE',
}
export const addSkills={
  ADD_SKILL_REQUEST:'ADD_SKILL_REQUEST',
  ADD_SKILL_SUCCESS:'ADD_SKILL_SUCCESS',
  ADD_SKILL_FAIL:'ADD_SKILL_FAIL'
}

export const addProfile={
  ADD_PROFILE_REQUEST:'ADD_PROFILE_REQUEST',
  ADD_PROFILE_SUCCESS:'ADD_PROFILE_SUCCESS',
  ADD_PROFILE_FAIL:'ADD_PROFILE_FAIL'
}


export const DashBoard = {
  GET_POSTINGS:'GET_POSTINGS'
}
export const Internships = {
  GET_INTERNSHIP:'GET_INTERNSHIP',
  GET_CATEGORIES:'GET_CATEGORIES',
  GET_FEATURED_JOBS:'GET_FEATURED_JOBS',

}